# Generated by Django 4.2.3 on 2023-07-13 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commet', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 7, 13, 22, 59, 25, 409321))),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='data.profile')),
            ],
        ),
    ]
