# Generated by Django 4.2.3 on 2023-07-15 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_profile_comments_comment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('msg', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 7, 15, 15, 44, 37, 727713))),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 15, 44, 37, 727713)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='default/user3.png', null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
