# Generated by Django 4.2.3 on 2023-07-15 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_usermsg_user_alter_comment_time_alter_usermsg_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='name_f',
        ),
        migrations.AddField(
            model_name='profile',
            name='name_l',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 15, 56, 54, 52506)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 15, 56, 54, 52506)),
        ),
    ]
