# Generated by Django 4.2.3 on 2023-07-16 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_usermsg_name_usermsg_name_f_usermsg_name_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermsg',
            name='name_for_nonUser',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 3, 0, 32, 612333)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 3, 0, 32, 613345)),
        ),
    ]
