# Generated by Django 4.2.3 on 2023-07-17 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_profile_admin_profile_assistant_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutS1', models.TextField(default=True, max_length=1000, null=True)),
                ('aboutS2', models.TextField(default=True, max_length=1000, null=True)),
                ('aboutS3', models.TextField(default=True, max_length=1000, null=True)),
                ('aboutS4', models.TextField(default=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 2, 23, 14, 454167)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 2, 23, 14, 454167)),
        ),
    ]
