# Generated by Django 4.2.3 on 2023-07-29 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_plog_plogimg_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Project-Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Project-Description', max_length=400, null=True)),
                ('img1', models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d')),
                ('img2', models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d')),
                ('img3', models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 3, 42, 12, 27482)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 3, 42, 12, 28522)),
        ),
    ]
