# Generated by Django 4.2.3 on 2023-07-31 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_project_img1_remove_project_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 20, 55, 47, 726042)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 20, 55, 47, 727062)),
        ),
    ]
