# Generated by Django 4.2.3 on 2023-08-03 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_project_img_alter_comment_time_alter_usermsg_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphoto',
            name='project',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 16, 20, 42, 681702)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 16, 20, 42, 681702)),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectPhoto',
        ),
    ]
