# Generated by Django 4.2.3 on 2023-08-03 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_remove_projectphoto_project_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Project-Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Project-Description', max_length=400, null=True)),
                ('img', models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 16, 21, 3, 852838)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 16, 21, 3, 852838)),
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d')),
                ('img2', models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d')),
                ('img3', models.ImageField(blank=True, default='default/product.png', null=True, upload_to='projects/%d')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='data.project')),
            ],
        ),
    ]
