# Generated by Django 4.2.3 on 2023-08-07 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_project_alter_comment_time_alter_usermsg_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='best',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 14, 0, 5, 961979)),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='img1',
            field=models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='img2',
            field=models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='img3',
            field=models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d'),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 14, 0, 5, 961979)),
        ),
    ]
