# Generated by Django 4.2.3 on 2023-08-09 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_comment_best_alter_comment_time_alter_project_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='inTheBest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 15, 56, 23, 511962)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 15, 56, 23, 512962)),
        ),
    ]
