# Generated by Django 4.2.3 on 2024-06-28 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_code_alter_comment_time_alter_lastsearch_search_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='data.project'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_area',
            field=models.TextField(default='<span class="nocode">no data founded</span>'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 12, 48, 44, 162621)),
        ),
        migrations.AlterField(
            model_name='lastsearch',
            name='search_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 28, 12, 48, 44, 168307), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 12, 48, 44, 167286)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 12, 48, 44, 162621)),
        ),
    ]
