# Generated by Django 4.2.3 on 2024-06-29 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_alter_code_project_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 0, 15, 38, 379040)),
        ),
        migrations.AlterField(
            model_name='lastsearch',
            name='search_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 30, 0, 15, 38, 379040), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 0, 15, 38, 379040)),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 0, 15, 38, 379040)),
        ),
    ]
