# Generated by Django 4.2.3 on 2024-07-01 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_project_status_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 33, 12, 915128)),
        ),
        migrations.AlterField(
            model_name='lastsearch',
            name='search_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 1, 23, 33, 12, 915128), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 33, 12, 915128)),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, default='http://none.com', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pnder update', 'Under Update'), ('Removed', 'Removed')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='img',
            field=models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/images/None'),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 33, 12, 915128)),
        ),
    ]
