# Generated by Django 4.2.3 on 2024-07-01 20:51

import data.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_alter_comment_time_alter_lastsearch_search_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 51, 47, 605066)),
        ),
        migrations.AlterField(
            model_name='lastsearch',
            name='search_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 1, 23, 51, 47, 607067), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 51, 47, 606067)),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='img',
            field=models.ImageField(blank=True, default='default/project.png', null=True, upload_to=data.models.projectname),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 51, 47, 605066)),
        ),
    ]
